### ISSUE TITLE
Cannot find module 'yeoman-generator'

### ISSUE THREAD

**Issue by onewaterdrop** [yeoman/generator-angular#1012]
npm 2.5.1
node v0.12.0
yo angular  

nerator-angular\app\index.js
   create     app\scripts\controllers\main.js
   create     test\spec\controllers\main.js
module.js:338
    throw err;
    ^
Error: Cannot find module 'yeoman-generator'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\youk\AppData\Roaming\npm\node_modules\genera
tor-karma\app\index.js:3:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by sindresorhus** [comment]
That looks like an npm install issue. Try StackOverflow or https://github.com/npm/npm/issues
