### ISSUE TITLE
Yo angular generator looking in wrong directory for bower.json

### ISSUE THREAD

**Issue by rubinovitz** [yeoman/generator-angular#1061]
I run
```
yo angular:route routeName
```
and get 
```
module.js:338
    throw err;
    ^
Error: Cannot find module '/Users/j/repos/bower.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at new Generator (/usr/local/lib/node_modules/generator-angular/route/index.js:17:15)
    at Environment.instantiate (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:282:10)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:259:15)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:318:24)
    at /usr/local/lib/node_modules/yo/lib/cli.js:86:9
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:50:12)
```

But my bower.json is in the directory I am running this command in, and is in a directory in repos.

**Comment by eddiemonge** [comment]
What directory are you running it in?

**Comment by rubinovitz** [comment]
/Users/j/repos/myapp

**Comment by eddiemonge** [comment]
do you have a .bowerrc or other file like that in `/Users/j/repos`?

**Comment by eddiemonge** [comment]
Closing due to inactivity. If its still a problem please let me know

**Comment by jonathanherdt** [comment]
I also had that problem. It resulted from me using yeoman to create an angular app in one folder and then moving that app to another folder.

I could remedy the situation by removing the yeoman file .yo-rc.json in the folder that I had used initially to create the app:
```rm yo-rc.json```
