### ISSUE TITLE
yo angular error

### ISSUE THREAD

**Issue by JinmingHao** [yeoman/generator-angular#1088]
module.js:338
    throw err;
          ^
Error: Cannot find module 'coffee-script'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/vagrant/MyProjects/yo-in-action/node_modules/grunt/lib/grunt.js:16:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by eddiemonge** [comment]
How did you get this error?

**Comment by sindresorhus** [comment]
You seem to have not run `npm install` or have suffered an npm install corruption. Upgrade to latest Node.js and npm (`$ npm install -g npm`) and reinstall.

npm support: https://github.com/npm/npm/issues

**Comment by JinmingHao** [comment]
I just start an angular app follow the steps yeman official site offers, when i run npm list, it shows below:

vagrant@vagrant-ubuntu-trusty-64:~/MyProjects/yo-in-action$ npm list
npm WARN unmet dependency /home/vagrant/MyProjects/yo-in-action/node_modules/grunt requires coffee-script@'~1.3.3' but will load
npm WARN unmet dependency /home/vagrant/MyProjects/yo-in-action/node_modules/coffee-script,
npm WARN unmet dependency which is version 1.9.2
npm WARN unmet dependency /home/vagrant/MyProjects/yo-in-action/node_modules/grunt-contrib-uglify/node_modules/maxmin requires chalk@'^1.0.0' but will load
npm WARN unmet dependency /home/vagrant/MyProjects/yo-in-action/node_modules/grunt-contrib-uglify/node_modules/chalk,
npm WARN unmet dependency which is version 0.5.1
npm WARN unmet dependency /home/vagrant/MyProjects/yo-in-action/node_modules/grunt-contrib-connect/node_modules/portscanner requires async@'0.1.15' but will load
npm WARN unmet dependency /home/vagrant/MyProjects/yo-in-action/node_modules/grunt-contrib-connect/node_modules/async,
npm WARN unmet dependency which is version 0.9.0
npm WARN unmet dependency /home/vagrant/MyProjects/yo-in-action/node_modules/grunt-google-cdn/node_modules/bower requires chalk@'^1.0.0' but will load
npm WARN unmet dependency /home/vagrant/MyProjects/yo-in-action/node_modules/grunt-google-cdn/node_modules/chalk,
npm WARN unmet dependency which is version 0.5.1
npm WARN unmet dependency /home/vagrant/MyProjects/yo-in-action/node_modules/grunt-google-cdn/node_modules/google-cdn requires bower@'~1.3.1' but will load
npm WARN unmet dependency /home/vagrant/MyProjects/yo-in-action/node_modules/grunt-google-cdn/node_modules/bower,
npm WARN unmet dependency which is version 1.4.1
yoinaction@0.0.0 /home/vagrant/MyProjects/yo-in-action
├── coffee-script@1.9.2 invalid
├─┬ grunt@0.4.5
│ ├── UNMET DEPENDENCY async@~0.1.22
│ ├── UNMET DEPENDENCY colors@~0.6.2
│ ├── UNMET DEPENDENCY dateformat@1.0.2-1.2.3
│ ├── UNMET DEPENDENCY eventemitter2@~0.4.13
│ ├── UNMET DEPENDENCY exit@~0.1.1
│ ├── UNMET DEPENDENCY findup-sync@~0.1.2
│ ├── UNMET DEPENDENCY getobject@~0.1.0
│ ├── UNMET DEPENDENCY glob@~3.1.21
│ ├── UNMET DEPENDENCY hooker@~0.2.3
│ ├── UNMET DEPENDENCY iconv-lite@~0.2.11
│ ├── UNMET DEPENDENCY js-yaml@~2.0.5
│ ├── UNMET DEPENDENCY lodash@~0.9.2
│ ├── UNMET DEPENDENCY minimatch@~0.2.12
│ ├── UNMET DEPENDENCY nopt@~1.0.10
│ ├── UNMET DEPENDENCY rimraf@~2.2.8
│ ├── UNMET DEPENDENCY underscore.string@~2.2.1

.......

npm ERR! missing: async@~0.1.22, required by grunt@0.4.5
npm ERR! missing: colors@~0.6.2, required by grunt@0.4.5
npm ERR! missing: dateformat@1.0.2-1.2.3, required by grunt@0.4.5
npm ERR! missing: eventemitter2@~0.4.13, required by grunt@0.4.5
npm ERR! missing: findup-sync@~0.1.2, required by grunt@0.4.5
npm ERR! missing: glob@~3.1.21, required by grunt@0.4.5
npm ERR! missing: hooker@~0.2.3, required by grunt@0.4.5
npm ERR! missing: iconv-lite@~0.2.11, required by grunt@0.4.5
npm ERR! missing: minimatch@~0.2.12, required by grunt@0.4.5
npm ERR! missing: nopt@~1.0.10, required by grunt@0.4.5
npm ERR! missing: rimraf@~2.2.8, required by grunt@0.4.5
npm ERR! missing: lodash@~0.9.2, required by grunt@0.4.5
npm ERR! missing: underscore.string@~2.2.1, required by grunt@0.4.5
npm ERR! missing: which@~1.0.5, required by grunt@0.4.5
npm ERR! missing: js-yaml@~2.0.5, required by grunt@0.4.5
npm ERR! missing: exit@~0.1.1, required by grunt@0.4.5
npm ERR! missing: getobject@~0.1.0, required by grunt@0.4.5
npm ERR! missing: async@0.9.0, required by grunt-newer@1.1.0
npm ERR! missing: rimraf@2.2.8, required by grunt-newer@1.1.0
npm ERR! missing: hooker@^0.2.3, required by grunt-contrib-jshint@0.11.2
npm ERR! missing: jshint@^2.6.0, required by grunt-contrib-jshint@0.11.2

my packages version like below:

vagrant@vagrant-ubuntu-trusty-64:~/MyProjects/yo-in-action$ node --version && npm --version && yo --version
v0.12.2
2.7.4
1.4.6

and when i run grunt --version in my project directory , it shows

vagrant@vagrant-ubuntu-trusty-64:~/MyProjects/yo-in-action$ grunt --version
grunt-cli v0.1.13
module.js:338
    throw err;
          ^
Error: Cannot find module 'dateformat'
  at Function.Module._resolveFilename (module.js:336:15)
  at Function.Module._load (module.js:278:25)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/home/vagrant/MyProjects/yo-in-action/node_modules/grunt/lib/grunt/template.js:18:17)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at gRequire (/home/vagrant/MyProjects/yo-in-action/node_modules/grunt/lib/grunt.js:23:24)
  at Object.<anonymous> (/home/vagrant/MyProjects/yo-in-action/node_modules/grunt/lib/grunt.js:34:1)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/usr/lib/node_modules/grunt-cli/bin/grunt:45:1)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3

should i install all missing packages manually?

**Comment by eddiemonge** [comment]
yes

**Comment by JinmingHao** [comment]
@eddiemonge ？？

**Comment by JinmingHao** [comment]
@eddiemonge so many dependencies

**Comment by JinmingHao** [comment]
I just confused why these errors happened , I followed the toturial completely.
