### ISSUE TITLE
Yo angular throws error without completing

### ISSUE THREAD

**Issue by youfacepalm** [yeoman/generator-angular#1159]
Node: v0.12.6
npm: v2.11.2
yo: v1.4.7
generator-angular:v0.12.1
Mac OS X: 10.10.3

? Would you like to use Sass (with Compass)? No
? Would you like to include Bootstrap? No
? Which modules would you like to include? angular-animate.js, angular-cookies.js, angular-resource.js, angular-route.js, angular-sanitize.js, angular-touch.js
   create app/styles/main.css
   create app/index.html
   create bower.json
   create .bowerrc
   create package.json
   create Gruntfile.js
   create README.md
   invoke   angular:common:/usr/local/lib/node_modules/generator-angular/app/index.js
   create     .editorconfig
   create     .gitattributes
   create     .jshintrc
   create     .yo-rc.json
   create     .gitignore
   create     test/.jshintrc
   create     app/.buildignore
   create     app/.htaccess
   create     app/404.html
   create     app/favicon.ico
   create     app/robots.txt
   create     app/views/main.html
   create     app/images/yeoman.png
   invoke   angular:main:/usr/local/lib/node_modules/generator-angular/app/index.js
   create     app/scripts/app.js
   invoke   angular:controller:/usr/local/lib/node_modules/generator-angular/app/index.js
   create     app/scripts/controllers/main.js
   create     test/spec/controllers/main.js
module.js:338
    throw err;
    ^
Error: Cannot find module 'object-assign'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-karma/node_modules/yeoman-generator/node_modules/download/index.js:3:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

I get the above out put when I run 'yo angular'. How can this be resolved?

**Comment by youfacepalm** [comment]
doing npm install -g <missing module> fixed it
