### ISSUE TITLE
Install issue on Nodejs v4.0.0

### ISSUE THREAD

**Issue by KingWu** [yeoman/generator-angular#1182]
Try to install a test project though generator-angular on Node v4.0.0.
But, get these error.

```
bower jquery#>= 1.9.0                        validate 2.1.4 against git://github.com/jquery/jquery.git#>= 1.9.0
bower angular-resource#^1.3.0                 ECMDERR Failed to execute "git ls-remote --tags --heads         git://github.com/angular/bower-angular-resource.git", exit code of #128 fatal: unable to connect to    github.com: github.com[0: 192.30.252.128]: errno=Operation timed out

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.128]: errno=Operation timed out
module.js:338
    throw err;
    ^

Error: Cannot find module 'coffee-script'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/dev-kingwu/Sapper Solutions/Ballot System/testAngularYo/node_modules/grunt/lib/grunt.js:16:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by javarch** [comment]
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
[generator-angular] Install issue on Nodejs v4.0.0 (#1182)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'


Der Austausch von Nachrichten mit o.a. Absender via e-mail dient
ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen d�rfen
�ber dieses Medium nicht ausgetauscht werden.

Correspondence with a.m. sender via e-mail is only for information
purposes. This medium is not to be used for the exchange of legally-binding
communications.

**Comment by V1cHu** [comment]
try installing coffee-script  by `npm install -g coffee-script` and then run the generator again.

**Comment by javarch** [comment]
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] Install issue on Nodejs v4.0.0 (#1182)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'


Der Austausch von Nachrichten mit o.a. Absender via e-mail dient
ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen d�rfen
�ber dieses Medium nicht ausgetauscht werden.

Correspondence with a.m. sender via e-mail is only for information
purposes. This medium is not to be used for the exchange of legally-binding
communications.

**Comment by creativestudio** [comment]
@KingWu any luck solving this issue?

**Comment by eddiemonge** [comment]
The top part looks like a network error. The bottom part looks like npm didnt finish running either. Try `npm install && bower install`

**Comment by eddiemonge** [comment]
closing due to inactivity
