### ISSUE TITLE
Error running 'yo angular'

### ISSUE THREAD

**Issue by t00th** [yeoman/generator-angular#1193]
Hi, peculiar problem while trying to run the angular generator. Not documented. Could be a permissions issue since npm was installed as root and yo wasn't. Not sure if that is causing this:

```
> node lib/install.js

  ⚠ Invalid non-string/buffer chunk
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ TypeError: Invalid non-string/buffer chunk
    at chunkInvalid (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:421:10)
    at readableAddChunk (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:176:12)
    at DuplexWrapper.Readable.push (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at DuplexWrapper._forwardRead (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:93:10)
    at DestroyableTransform.<anonymous> (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:50:10)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:460:10)
    at emitReadable (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:454:7)
    at readableAddChunk (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:209:11)

> gifsicle@3.0.1 postinstall /home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ⚠ Invalid non-string/buffer chunk
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ TypeError: Invalid non-string/buffer chunk
    at chunkInvalid (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:421:10)
    at readableAddChunk (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:176:12)
    at DuplexWrapper.Readable.push (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at DuplexWrapper._forwardRead (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:93:10)
    at DestroyableTransform.<anonymous> (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:50:10)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:460:10)
    at emitReadable (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:454:7)
    at readableAddChunk (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:209:11)

> jpegtran-bin@3.0.5 postinstall /home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ Invalid non-string/buffer chunk
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ TypeError: Invalid non-string/buffer chunk
    at chunkInvalid (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:421:10)
    at readableAddChunk (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:176:12)
    at DuplexWrapper.Readable.push (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at DuplexWrapper._forwardRead (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:93:10)
    at DestroyableTransform.<anonymous> (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:50:10)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:460:10)
    at emitReadable (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:454:7)
    at readableAddChunk (/home/t00th/w/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:209:11)
npm ERR! Linux 3.19.0-15-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! path /home/t00th/.npm/strip-ansi/0.2.2
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/home/t00th/.npm/strip-ansi/0.2.2'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/home/t00th/.npm/strip-ansi/0.2.2']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/t00th/.npm/strip-ansi/0.2.2',
npm ERR!   parent: 'string-length' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/t00th/w/mytodo/npm-debug.log
Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Done, without errors.


Execution Time (2015-10-17 04:06:34 UTC)
loading tasks           13ms  ▇▇▇ 6%
loading grunt-wiredep    9ms  ▇▇ 4%
wiredep:app            178ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 82%
wiredep:test            15ms  ▇▇▇ 7%
Total 216ms

? Overwrite package.json? overwrite
    force     package.json
   create     .travis.yml
npm WARN peerDependencies The peer dependency jasmine-core@* included from karma-jasmine will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency karma@>=0.9 included from karma-phantomjs-launcher will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency phantomjs@>=1.9 included from karma-phantomjs-launcher will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency karma@^0.13.0 || >= 0.14.0-rc.0 included from grunt-karma will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@1.0.2
 
> phantomjs@1.9.18 install /home/t00th/w/mytodo/node_modules/phantomjs
> node install.js

Download already available at /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Extracting tar contents (via spawned process)
Removing /home/t00th/w/mytodo/node_modules/phantomjs/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1445055173914/phantomjs-1.9.8-linux-x86_64 -> /home/t00th/w/mytodo/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/t00th/w/mytodo/node_modules/phantomjs/lib/phantom/bin/phantomjs
 
> utf-8-validate@1.2.1 install /home/t00th/w/mytodo/node_modules/karma/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/home/t00th/w/mytodo/node_modules/karma/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/home/t00th/w/mytodo/node_modules/karma/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'

> bufferutil@1.2.1 install /home/t00th/w/mytodo/node_modules/karma/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/home/t00th/w/mytodo/node_modules/karma/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/home/t00th/w/mytodo/node_modules/karma/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'

> bufferutil@1.2.1 install /home/t00th/w/mytodo/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/home/t00th/w/mytodo/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/home/t00th/w/mytodo/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /home/t00th/w/mytodo/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/home/t00th/w/mytodo/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/home/t00th/w/mytodo/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'
npm ERR! Linux 3.19.0-15-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! path /home/t00th/.npm/strip-ansi/0.2.2
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/home/t00th/.npm/strip-ansi/0.2.2'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/home/t00th/.npm/strip-ansi/0.2.2']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/t00th/.npm/strip-ansi/0.2.2',
npm ERR!   parent: 'string-length' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/t00th/w/mytodo/npm-debug.log
```

But then, if I run 'grunt serve,' a perfect-looking website pops up, 0 errors on terminal. So I would like to know if this is something I should worry about that might affect my application later on, or if this is just one of those errors that you can ignore.

Thanks,
t00th

**Comment by eddiemonge** [comment]
you really shouldnt have npm as root. You might run in to other issues later. And yes it looks like a permission mismatch
