### ISSUE TITLE
angular:controller generates coffeescript files even when flag is set to false.

### ISSUE THREAD

**Issue by wilblack** [yeoman/generator-angular#1219]
My project is written in regular javascript and used to work fine. I have check for .coffee files and the only ones I have found are in node_models at the project root. Could these be the problem? Below is some sample output.

```
 $ yo angular:controller fsEditor  --coffee=false
   create app/scripts/controllers/fseditor.coffee
   create test/spec/controllers/fseditor.coffee
```

Also if I run the route command it fails because it is looking for app.coffee.

```
yo angular:route fsEditor  --coffee=false
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'app/scripts/app.coffee'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at new Generator (/usr/local/lib/node_modules/generator-angular/route/index.js:20:29)
    at Environment.instantiate (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:297:10)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:274:15)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:333:24)
    at /usr/local/lib/node_modules/yo/lib/cli.js:99:9
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:50:12)
    at init (/usr/local/lib/node_modules/yo/lib/cli.js:72:7)
```

**Comment by eddiemonge** [comment]
Don't add the flag at all. Adding it is the same as setting it to true
