### ISSUE TITLE
yo angular does not work for me

### ISSUE THREAD

**Issue by roestigraben** [yeoman/generator-angular#1220]
Hi there,

the generator used to work for me but recently I get this below

other generators like web-app run fine.

tried to update everything
versions used :  
 - node    4.2.2
 - npm 3.5.8

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-angular/node_modules/findup-sync/node_modules/glob/glob.js:42:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

**Comment by cseto** [comment]
experiencing similar problem with npm install
node 4.2.2
npm --version throws similar module.js error
git version 1.9.5.msysgit.1
----
λ npm install -g grunt-cli bower yo generator-karma generator-angular
module.js:339
    throw err;
    ^

Error: Cannot find module 'has-unicode'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\progress-bar.js:2:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
 module.js:339
    throw err;
    ^

Error: Cannot find module 'has-unicode'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\progress-bar.js:2:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

**Comment by eddiemonge** [comment]
Have you tried running the install again? This looks like an npm issue especially since it happens during install. Please open an issue there about it as there isn't much, if anything, that can be done here. Thanks.
