### ISSUE TITLE
yo angular app-name fails windows 10, node-js 5.1

### ISSUE THREAD

**Issue by pulkitnandan** [yeoman/generator-angular#1228]
├── UNMET PEER DEPENDENCY karma@>=0.10 <=0.13
├─┬ lazypipe@0.2.4
│ └── stream-combiner@0.0.4
├── open@0.0.5
├── rimraf@2.4.4
├── run-sequence@1.1.5
└─┬ wiredep@2.2.2
  ├─┬ bower-config@0.5.2
  │ ├── graceful-fs@2.0.3
  │ ├── mout@0.9.1
  │ └── osenv@0.0.3
  ├─┬ chalk@0.5.1
  │ ├── ansi-styles@1.1.0
  │ ├─┬ has-ansi@0.1.0
  │ │ └── ansi-regex@0.2.1
  │ ├── strip-ansi@0.3.0
  │ └── supports-color@0.2.0
  ├─┬ glob@4.5.3
  │ └── minimatch@2.0.10
  ├── lodash@2.4.2
  ├── propprop@0.3.0
  └─┬ through2@0.6.5
    └── readable-stream@1.0.33

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.5
npm WARN gulp-karma@0.0.4 requires a peer of karma@>=0.10 <=0.13 but none was installed.
[18:21:18] Using gulpfile ~\frontend\gulpfile.js
[18:21:18] Task 'wiredep' is not in your gulpfile
[18:21:18] Please check the documentation for proper gulpfile formatting
? Overwrite package.json? overwrite
    force     package.json
   create     .travis.yml
frontend@ C:\Users\Rohit\frontend
├── UNMET PEER DEPENDENCY grunt@0.4.x
├─┬ grunt-karma@0.12.1
│ └── lodash@3.10.1
├─┬ gulp-imagemin@2.4.0
│ └─┬ imagemin@4.0.0
│   └─┬ imagemin-svgo@4.2.0
│     └─┬ svgo@0.6.1
│       └─┬ js-yaml@3.4.6
│         └─┬ argparse@1.0.3
│           └── lodash@3.10.1
├─┬ gulp-jshint@1.12.0
│ └── lodash@3.10.1
├─┬ gulp-useref@1.3.0
│ └── lodash@3.10.1
├── UNMET PEER DEPENDENCY jasmine-core@*
├── UNMET PEER DEPENDENCY karma@^0.13.0 || >= 0.14.0-rc.0
├── karma-jasmine@0.3.6
├─┬ karma-phantomjs-launcher@0.2.1
│ └── lodash@3.10.1
└── UNMET PEER DEPENDENCY phantomjs@>=1.9

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.5
npm WARN gulp-karma@0.0.4 requires a peer of karma@>=0.10 <=0.13 but none was installed.
npm WARN karma-jasmine@0.3.6 requires a peer of jasmine-core@* but none was installed.
npm WARN grunt-karma@0.12.1 requires a peer of grunt@0.4.x but none was installed.
npm WARN grunt-karma@0.12.1 requires a peer of karma@^0.13.0 || >= 0.14.0-rc.0 but none was installed.
npm WARN karma-phantomjs-launcher@0.2.1 requires a peer of karma@>=0.9 but none was installed.
npm WARN karma-phantomjs-launcher@0.2.1 requires a peer of phantomjs@>=1.9 but none was installed.

C:\Users\Rohit\frontend>
C:\Users\Rohit\frontend>gulp
[18:24:25] Using gulpfile ~\frontend\gulpfile.js
[18:24:25] Starting 'clean:dist'...
[18:24:25] Finished 'clean:dist' after 3.76 ms
[18:24:25] Starting 'build'...
[18:24:25] Starting 'images'...
[18:24:25] Starting 'copy:extras'...
[18:24:25] Starting 'copy:fonts'...
[18:24:25] Starting 'html'...
[18:24:25] Starting 'styles'...
[18:24:25] Finished 'build' after 566 ms
[18:24:25] Starting 'default'...
[18:24:25] Finished 'default' after 15 μs
[18:24:25] Finished 'copy:fonts' after 42 ms
[18:24:25] Finished 'copy:extras' after 55 ms
[18:24:25] Finished 'images' after 727 ms
[18:24:25] Finished 'styles' after 172 ms
[18:24:25] Finished 'html' after 178 ms
[18:24:25] Starting 'client:build'...
[18:24:26] 'client:build' errored after 683 ms
[18:24:26] TypeError: $.useref.restore is not a function
    at Gulp.<anonymous> (C:\Users\Rohit\frontend\gulpfile.js:167:20)
    at module.exports (C:\Users\Rohit\frontend\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\Rohit\frontend\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\Rohit\frontend\node_modules\orchestrator\index.js:214:10)
    at C:\Users\Rohit\frontend\node_modules\orchestrator\index.js:279:18
    at finish (C:\Users\Rohit\frontend\node_modules\orchestrator\lib\runTask.js:21:8)
    at C:\Users\Rohit\frontend\node_modules\orchestrator\lib\runTask.js:52:4
    at f (C:\Users\Rohit\frontend\node_modules\once\once.js:17:25)
    at DestroyableTransform.onend (C:\Users\Rohit\frontend\node_modules\end-of-stream\index.js:31:18)
    at emitNone (events.js:72:20)
    at DestroyableTransform.emit (events.js:166:7)
    at C:\Users\Rohit\frontend\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
[18:24:26] Error in plugin 'run-sequence'
Message:
    An error occured in task 'client:build'.

**Comment by pulkitnandan** [comment]
Above seems to be because of gulp but with grunt following error

C:\Users\Rohit\ad-analytics\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\Rohit\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Python34;C:\Python34\Scripts\", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Rohit\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Users\Rohit\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Rohit\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Rohit\ad-analytics\node_modules\bufferutil
gyp ERR! node -v v5.1.1
gyp ERR! node-gyp -v v3.2.0
gyp ERR! not ok
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install C:\Users\Rohit\ad-analytics\node_modules\utf-8-validate
> node-gyp rebuild


C:\Users\Rohit\ad-analytics\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\Rohit\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Python34;C:\Python34\Scripts\", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Rohit\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Users\Rohit\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Rohit\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Rohit\ad-analytics\node_modules\utf-8-validate
gyp ERR! node -v v5.1.1
gyp ERR! node-gyp -v v3.2.0
gyp ERR! not ok
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 1

> phantomjs@1.9.19 install C:\Users\Rohit\ad-analytics\node_modules\phantomjs
> node install.js


Install phantomjs, jasmine-core, karma manually.
