### ISSUE TITLE
"yo angular" failed with error on mac

### ISSUE THREAD

**Issue by vijayendra** [yeoman/generator-angular#1248]
Hi,

I'm using npm version 3.5.3. Trying to use yo angular command to test angular app but it failed with error:

```
$ yo angular

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |    Welcome to Yeoman,    |
   `---------´   |   ladies and gentlemen!  |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

Out of the box I include Bootstrap and some AngularJS recommended modules.

? Would you like to use Gulp (experimental) instead of Grunt? No
? Would you like to use Sass (with Compass)? Yes
? Would you like to include Bootstrap? Yes
? Would you like to use the Sass version of Bootstrap? Yes
? Which modules would you like to include? angular-animate.js, angular-aria.js, angular-cookies.js, angular-resource.js, angular-messages.js, angu
identical app/styles/main.scss.js, angular-touch.js
 conflict app/index.html
? Overwrite app/index.html? overwrite
    force app/index.html
identical bower.json
identical .bowerrc
identical package.json
identical Gruntfile.js
identical README.md
   invoke   angular:common:/Users/vijay/testapp/node_modules/generator-angular/app/index.js
identical     .editorconfig
identical     .gitattributes
identical     .jscsrc
identical     .jshintrc
identical     .yo-rc.json
identical     .gitignore
identical     test/.jshintrc
identical     app/404.html
identical     app/favicon.ico
identical     app/robots.txt
identical     app/views/main.html
identical     app/images/yeoman.png
   invoke   angular:main:/Users/vijay/testapp/node_modules/generator-angular/app/index.js
 conflict     app/scripts/app.js
? Overwrite app/scripts/app.js? overwrite
    force     app/scripts/app.js
   invoke   angular:controller:/Users/vijay/testapp/node_modules/generator-angular/app/index.js
identical     app/scripts/controllers/main.js
identical     test/spec/controllers/main.js
   invoke   karma:app


I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.


   invoke       angular:route
   invoke           angular:controller:/Users/vijay/testapp/node_modules/generator-angular/route/index.js
identical             app/scripts/controllers/about.js
identical             test/spec/controllers/about.js
   invoke           angular:view:/Users/vijay/testapp/node_modules/generator-angular/route/index.js
identical             app/views/about.html
identical     test/karma.conf.js
 conflict     package.json
npm ERR! fetch failed http://github.com/yeoman/generators/archive/0.9.5.tar.gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm WARN excluding symbolic link test/fixtures/octocat-link.png -> octocat.png
npm ERR! fetch failed http://github.com/yeoman/generators/archive/0.9.5.tar.gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed http://github.com/yeoman/generators/archive/0.9.5.tar.gz
npm WARN deprecated CSSselect@0.7.0: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
- yeoman@0.9.6 node_modules/yeoman
npm WARN optional Skipping failed optional dependency /yeoman/yeoman-generators:
npm WARN fetch failed with status code 404


events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn grunt ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

```

**Comment by eddiemonge** [comment]
Have you tried with a clean directory as I can't really tell whats failing here with all the duplicates and symlinked things.

**Comment by agencia** [comment]
+1 same here with a clean directory

**Comment by agencia** [comment]
I have had this issue for quite some time, I ran

```
sudo npm install -g grunt-cli
```

And my problems are gone

**Comment by eddiemonge** [comment]
You should really be running sudo-less npm. Running it causes so many problems, not the least of which is that you are seriously compromising your system's security.

**Comment by agencia** [comment]
Actually if I do it sudoless it throws an error that says I should do it as
admin

so this is confusing

**Comment by eddiemonge** [comment]
You installed it as sudo. Do a search on how to install npm sudoless. It will make your life easier

**Comment by jookes** [comment]
Follow this guide to fix the problem of installing npm (or any other dependency) with sudo. 
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by hackjustu** [comment]
+1 failed for the same reason reliably

**Comment by niyando** [comment]
did anyone find a solution for this issue? I don't get any scaffold created in my folder and when trying to run it again it gives me file conflicts as if I am trying to run the generator in a folder with existing app.

**Comment by eddiemonge** [comment]
@niyando your problem sounds like you have a `.yo-rc.json` file somewhere in a parent folder and thats where the files are getting generated

Closing this as it is a npm issue

**Comment by niyando** [comment]
Yes. I had a .yo-rc.json in parent folder. Deleting it solved the issue. Thanks.
