### ISSUE TITLE
how to [grunt build] with ES6

### ISSUE THREAD

**Issue by axetroy** [yeoman/generator-angular#1265]
i want to use ES6 to build my APP.
but this generator don't support to build with ES6.

whe i add some ES6 code in my js file
```js
  .run(function ($timeout) {
    $timeout(()=>{
      alert(123);
    });
  });
```
and the run `grunt serve`
yeah!
it will be runed like expected,everything is ok.

but when i want to public my app,and build it with `grunt build`
it won't transform ES6 to ES5,so bring about some error like this:
```bash
Running "uglify:generated" (uglify) task
JS_Parse_Error {
  message: 'Unexpected token: punc ())',
  filename: '../../.tmp/concat/scripts/scripts.js',
  line: 37,
  col: 14,
  pos: 739,
  stack: 'Error\n    at new JS_Parse_Error (/home/axetroy/developer/angular/angular-test/node_modules/uglify-js/lib/parse.js:196:18)\n    at js_error (/home/axetroy/developer/angular/angular-test/node_modules/uglify-js/lib/parse.js:204:11)\n    at croak (/home/axetroy/developer/angular/angular-test/node_modules/uglify-js/lib/parse.js:680:9)\n    at token_error (/home/axetroy/developer/angular/angular-test/node_modules/uglify-js/lib/parse.js:688:9)\n    at unexpected (/home/axetroy/developer/angular/angular-test/node_modules/uglify-js/lib/parse.js:694:9)\n    at expr_atom (/home/axetroy/developer/angular/angular-test/node_modules/uglify-js/lib/parse.js:1189:13)\n    at maybe_unary (/home/axetroy/developer/angular/angular-test/node_modules/uglify-js/lib/parse.js:1363:19)\n    at expr_ops (/home/axetroy/developer/angular/angular-test/node_modules/uglify-js/lib/parse.js:1398:24)\n    at maybe_conditional (/home/axetroy/developer/angular/angular-test/node_modules/uglify-js/lib/parse.js:1403:20)\n    at maybe_assign (/home/axetroy/developer/angular/angular-test/node_modules/uglify-js/lib/parse.js:1427:20)' }
>> Uglifying source .tmp/concat/scripts/scripts.js failed.
Warning: Uglification failed.
Unexpected token: punc ()). 
Line 37 in .tmp/concat/scripts/scripts.js
 Use --force to continue.

Aborted due to warnings.
```

so ,how to fixed this?
ty

**Comment by eddiemonge** [comment]
You have to add something like Babel to transpile it.
