### ISSUE TITLE
yo angular-fullstack endpoint issue

### ISSUE THREAD

**Issue by syndrom95** [yeoman/generator-angular#1305]
Hello there, I'm fairly new with yeoman so the probability is I've done something wrong so I'm having troubles.

Problem:

I set up my project and it worked since I haven't done anything as of yet. Then I went to install yo angular-fullstack:endpoint travels and it created new files at it should, but then when I ran grunt serve I get this error : 

````
C:\Users\HP\Desktop\og2\starter-project\server\api\travel\travel.controller.js:9
export function index(req, res) {
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\HP\Desktop\og2\starter-project\server\api\travel\index.js:4:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (C:\Users\HP\Desktop\og2\starter-project\server\routes.js:13:27)
    at Object.<anonymous> (C:\Users\HP\Desktop\og2\starter-project\server\app.js:28:20)
```
`

Can anyone help me resolve this, or what the issue is?

**Comment by eddiemonge** [comment]
You should ask this on generator-angular-fullstack. But it sounds like you haven't setup Babel yet
