### ISSUE TITLE
Error: Cannot find module '../lib/bin/bower'

### ISSUE THREAD

**Issue by Sharadb2bcom** [yeoman/generator-angular#1374]
When i am trying to do a build i am getting this issue 
```
Error: Cannot find module '../lib/bin/bower'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/shardpawar/work/OT/mwallet-2.5-updated/mwallet-2.5/angular-uis/build/tmp/node_modules/.bin/bower:3:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by eddiemonge** [comment]
have you tried running `npm install && npm update` again to see if something was broken originally?

**Comment by saifalfalah** [comment]
Removing everything from the node_modules folder and running `npm install` usually works.

**Comment by eddiemonge** [comment]
closing due inactivity
