### ISSUE TITLE
Grunt breaks no matter what

### ISSUE THREAD

**Issue by qstrahl** [yeoman/generator-angular#275]
# The Problem

Two things:
- Doing just about anything with grunt causes it to yell at me about this:

```
Loading "cdnify.js" tasks...ERROR
>> Error: Unable to create git_template directory: Arguments to path.resolve must be strings
```
- Grunt stops running tasks due to warnings that fail to materialize with either the `--verbose` or `--debug` flags; I can straight up remove the offending code from the stack trace and receive no negative output from grunt despite it failing to proceed to do what I want it to:

```
    Done, without errors.
        Warning:  Use --force to continue.

        Aborted due to warnings.
```
# `grunt -v`

```
Initializing
Command-line options: --no-color, --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-contrib-copy" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-copy/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-copy/package.json...OK
Loading "copy.js" tasks...OK
+ copy

Registering "grunt-contrib-concat" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-concat/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-concat/package.json...OK
Loading "concat.js" tasks...OK
+ concat

Registering "grunt-contrib-coffee" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-coffee/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-coffee/package.json...OK
Loading "coffee.js" tasks...OK
+ coffee

Registering "grunt-contrib-uglify" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-uglify/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-uglify/package.json...OK
Loading "uglify.js" tasks...OK
+ uglify

Registering "grunt-contrib-compass" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-compass/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-compass/package.json...OK
Loading "compass.js" tasks...OK
+ compass

Registering "grunt-contrib-jshint" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-jshint/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-jshint/package.json...OK
Loading "jshint.js" tasks...OK
+ jshint

Registering "grunt-contrib-cssmin" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-cssmin/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-cssmin/package.json...OK
Loading "cssmin.js" tasks...OK
+ cssmin

Registering "grunt-contrib-connect" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-connect/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-connect/package.json...OK
Loading "connect.js" tasks...OK
+ connect

Registering "grunt-contrib-clean" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-clean/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-clean/package.json...OK
Loading "clean.js" tasks...OK
+ clean

Registering "grunt-contrib-htmlmin" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-htmlmin/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-htmlmin/package.json...OK
Loading "htmlmin.js" tasks...OK
+ htmlmin

Registering "grunt-contrib-imagemin" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-imagemin/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-imagemin/package.json...OK
Loading "imagemin.js" tasks...OK
+ imagemin

Registering "grunt-contrib-watch" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-watch/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-watch/package.json...OK
Loading "watch.js" tasks...OK
+ watch

Registering "grunt-usemin" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-usemin/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-usemin/package.json...OK
Loading "usemin.js" tasks...OK
+ usemin, useminPrepare

Registering "grunt-rev" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-rev/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-rev/package.json...OK
Loading "rev.js" tasks...OK
+ rev

Registering "grunt-karma" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-karma/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-karma/package.json...OK
Loading "grunt-karma.js" tasks...OK
+ karma

Registering "grunt-open" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-open/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-open/package.json...OK
Loading "open.js" tasks...OK
+ open

Registering "grunt-concurrent" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-concurrent/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-concurrent/package.json...OK
Loading "concurrent.js" tasks...OK
+ concurrent

Registering "grunt-google-cdn" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-google-cdn/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-google-cdn/package.json...OK
Loading "cdnify.js" tasks...ERROR
>> Error: Unable to create git_template directory: Arguments to path.resolve must be strings
>>     at Object.<anonymous> (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-google-cdn/node_modules/bower/lib/core/config.js:68:9)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-karma/node_modules/karma/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at Object.<anonymous> (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-google-cdn/node_modules/bower/lib/commands/help.js:14:17)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-karma/node_modules/karma/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at Object.<anonymous> (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-google-cdn/node_modules/bower/lib/commands/index.js:10:18)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-karma/node_modules/karma/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at Object.<anonymous> (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-google-cdn/node_modules/bower/lib/index.js:10:16)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-karma/node_modules/karma/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at Object.<anonymous> (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-google-cdn/util/bower.js:4:19)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-karma/node_modules/karma/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at Object.<anonymous> (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-google-cdn/tasks/cdnify.js:5:13)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-karma/node_modules/karma/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at loadTask (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt/lib/grunt/task.js:310:10)
>>     at /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt/lib/grunt/task.js:348:7
>>     at Array.forEach (native)
>>     at loadTasks (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt/lib/grunt/task.js:347:11)
>>     at Task.task.loadNpmTasks (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt/lib/grunt/task.js:395:5)
>>     at Array.forEach (native)
>>     at Object.module.exports (/home/qstrahl/Projects/trialfire/web-client/Gruntfile.js:17:44)
>>     at loadTask (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt/lib/grunt/task.js:312:10)
>>     at Task.task.init (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt/lib/grunt/task.js:424:5)
>>     at Object.grunt.tasks (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt/lib/grunt.js:113:8)
>>     at Object.module.exports [as cli] (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt/lib/grunt/cli.js:38:9)
>>     at Object.<anonymous> (/usr/lib64/node_modules/grunt-cli/bin/grunt:41:20)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:312:12)
>>     at Function.Module.runMain (module.js:497:10)
>>     at startup (node.js:119:16)
>>     at node.js:901:3

Registering "grunt-ngmin" local Npm module tasks.
Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-ngmin/package.json...OK
Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-ngmin/package.json...OK
Loading "ngmin.js" tasks...OK
+ ngmin
Initializing config...OK
Loading "Gruntfile.js" tasks...OK
+ build, default, server, test

No tasks specified, running default tasks.
Running tasks: default

Running "default" task

Running "jshint" task

Running "jshint:all" (jshint) task
Verifying property jshint.all exists in config...OK
Files: Gruntfile.js, app/scripts/app.js, app/scripts/controllers/experiences.js, app/scripts/controllers/main.js, app/scripts/controllers/navigation.js, app/scripts/services/Experience.js, app/scripts/services/Goal.js, app/scripts/services/Navigation.js, app/scripts/services/Person.js -> all
Reading .jshintrc...OK
Parsing .jshintrc...OK
JSHint options: node, browser, esnext, bitwise, camelcase, curly, eqeqeq, immed, indent=2, latedef, newcap, noarg, quotmark="single", regexp, undef, unused, strict, trailing, smarttabs, globals={"angular":false}
OK
>> 9 files lint free.

Running "test" task

Running "clean:server" (clean) task
Verifying property clean.server exists in config...OK
Files: .tmp -> server
Options: force=false
Cleaning ".tmp"...Deleting .tmp...OK
OK

Running "concurrent:test" (concurrent) task
Verifying property concurrent.test exists in config...OK
Files: [no src] -> test

    Initializing
    Command-line options: --no-color, --verbose

    Reading "Gruntfile.js" Gruntfile...OK

    Registering Gruntfile tasks.

    Registering "grunt-contrib-copy" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-copy/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-copy/package.json...OK
    Loading "copy.js" tasks...OK
    + copy

    Registering "grunt-contrib-concat" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-concat/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-concat/package.json...OK
    Loading "concat.js" tasks...OK
    + concat

    Registering "grunt-contrib-coffee" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-coffee/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-coffee/package.json...OK
    Loading "coffee.js" tasks...OK
    + coffee

    Registering "grunt-contrib-uglify" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-uglify/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-uglify/package.json...OK
    Loading "uglify.js" tasks...OK
    + uglify

    Registering "grunt-contrib-compass" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-compass/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-compass/package.json...OK
    Loading "compass.js" tasks...OK
    + compass

    Registering "grunt-contrib-jshint" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-jshint/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-jshint/package.json...OK
    Loading "jshint.js" tasks...OK
    + jshint

    Registering "grunt-contrib-cssmin" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-cssmin/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-cssmin/package.json...OK
    Loading "cssmin.js" tasks...OK
    + cssmin

    Registering "grunt-contrib-connect" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-connect/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-connect/package.json...OK
    Loading "connect.js" tasks...OK
    + connect

    Registering "grunt-contrib-clean" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-clean/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-clean/package.json...OK
    Loading "clean.js" tasks...OK
    + clean

    Registering "grunt-contrib-htmlmin" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-htmlmin/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-htmlmin/package.json...OK
    Loading "htmlmin.js" tasks...OK
    + htmlmin

    Registering "grunt-contrib-imagemin" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-imagemin/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-imagemin/package.json...OK
    Loading "imagemin.js" tasks...OK
    + imagemin

    Registering "grunt-contrib-watch" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-watch/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-contrib-watch/package.json...OK
    Loading "watch.js" tasks...OK
    + watch

    Registering "grunt-usemin" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-usemin/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-usemin/package.json...OK
    Loading "usemin.js" tasks...OK
    + usemin, useminPrepare

    Registering "grunt-rev" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-rev/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-rev/package.json...OK
    Loading "rev.js" tasks...OK
    + rev

    Registering "grunt-karma" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-karma/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-karma/package.json...OK
    Loading "grunt-karma.js" tasks...OK
    + karma

    Registering "grunt-open" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-open/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-open/package.json...OK
    Loading "open.js" tasks...OK
    + open

    Registering "grunt-concurrent" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-concurrent/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-concurrent/package.json...OK
    Loading "concurrent.js" tasks...OK
    + concurrent

    Registering "grunt-google-cdn" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-google-cdn/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-google-cdn/package.json...OK
    Loading "cdnify.js" tasks...ERROR
    >> Error: Unable to create git_template directory: Arguments to path.resolve must be strings
    >>     at Object.<anonymous> (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-google-cdn/node_modules/bower/lib/core/config.js:68:9)
    >>     at Module._compile (module.js:456:26)
    >>     at Object.Module._extensions..js (module.js:474:10)
    >>     at Module.load (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-karma/node_modules/karma/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    >>     at Function.Module._load (module.js:312:12)
    >>     at Module.require (module.js:364:17)
    >>     at require (module.js:380:17)
    >>     at Object.<anonymous> (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-google-cdn/node_modules/bower/lib/commands/help.js:14:17)
    >>     at Module._compile (module.js:456:26)
    >>     at Object.Module._extensions..js (module.js:474:10)
    >>     at Module.load (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-karma/node_modules/karma/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    >>     at Function.Module._load (module.js:312:12)
    >>     at Module.require (module.js:364:17)
    >>     at require (module.js:380:17)
    >>     at Object.<anonymous> (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-google-cdn/node_modules/bower/lib/commands/index.js:10:18)
    >>     at Module._compile (module.js:456:26)
    >>     at Object.Module._extensions..js (module.js:474:10)
    >>     at Module.load (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-karma/node_modules/karma/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    >>     at Function.Module._load (module.js:312:12)
    >>     at Module.require (module.js:364:17)
    >>     at require (module.js:380:17)
    >>     at Object.<anonymous> (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-google-cdn/node_modules/bower/lib/index.js:10:16)
    >>     at Module._compile (module.js:456:26)
    >>     at Object.Module._extensions..js (module.js:474:10)
    >>     at Module.load (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-karma/node_modules/karma/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    >>     at Function.Module._load (module.js:312:12)
    >>     at Module.require (module.js:364:17)
    >>     at require (module.js:380:17)
    >>     at Object.<anonymous> (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-google-cdn/util/bower.js:4:19)
    >>     at Module._compile (module.js:456:26)
    >>     at Object.Module._extensions..js (module.js:474:10)
    >>     at Module.load (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-karma/node_modules/karma/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    >>     at Function.Module._load (module.js:312:12)
    >>     at Module.require (module.js:364:17)
    >>     at require (module.js:380:17)
    >>     at Object.<anonymous> (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-google-cdn/tasks/cdnify.js:5:13)
    >>     at Module._compile (module.js:456:26)
    >>     at Object.Module._extensions..js (module.js:474:10)
    >>     at Module.load (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-karma/node_modules/karma/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    >>     at Function.Module._load (module.js:312:12)
    >>     at Module.require (module.js:364:17)
    >>     at require (module.js:380:17)
    >>     at loadTask (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt/lib/grunt/task.js:310:10)
    >>     at /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt/lib/grunt/task.js:348:7
    >>     at Array.forEach (native)
    >>     at loadTasks (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt/lib/grunt/task.js:347:11)
    >>     at Task.task.loadNpmTasks (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt/lib/grunt/task.js:395:5)
    >>     at Array.forEach (native)
    >>     at Object.module.exports (/home/qstrahl/Projects/trialfire/web-client/Gruntfile.js:17:44)
    >>     at loadTask (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt/lib/grunt/task.js:312:10)
    >>     at Task.task.init (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt/lib/grunt/task.js:424:5)
    >>     at Object.grunt.tasks (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt/lib/grunt.js:113:8)
    >>     at Object.module.exports [as cli] (/home/qstrahl/Projects/trialfire/web-client/node_modules/grunt/lib/grunt/cli.js:38:9)
    >>     at Object.<anonymous> (/usr/lib64/node_modules/grunt-cli/bin/grunt:41:20)
    >>     at Module._compile (module.js:456:26)
    >>     at Object.Module._extensions..js (module.js:474:10)
    >>     at Module.load (module.js:356:32)
    >>     at Function.Module._load (module.js:312:12)
    >>     at Function.Module.runMain (module.js:497:10)
    >>     at startup (node.js:119:16)
    >>     at node.js:901:3

    Registering "grunt-ngmin" local Npm module tasks.
    Reading /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-ngmin/package.json...OK
    Parsing /home/qstrahl/Projects/trialfire/web-client/node_modules/grunt-ngmin/package.json...OK
    Loading "ngmin.js" tasks...OK
    + ngmin
    Initializing config...OK
    Loading "Gruntfile.js" tasks...OK
    + build, default, server, test

    Running tasks: coffee

    Running "coffee" task

    Running "coffee:dist" (coffee) task
    Verifying property coffee.dist exists in config...OK
    Options: bare=false, join=false, sourceMap=false, separator="\n"

    Running "coffee:test" (coffee) task
    Verifying property coffee.test exists in config...OK
    Options: bare=false, join=false, sourceMap=false, separator="\n"

    Done, without errors.
        Warning:  Use --force to continue.

        Aborted due to warnings.
```
# `grunt --version`

```
grunt-cli v0.1.9
grunt v0.4.1
```
# `bower --version`

```
0.10.0
```
# `yo --version`

```
1.0.0-rc.1.1
```
# `node --version`

```
v0.11.2
```

**Comment by hugomosh** [comment]
´´´ npm install grunt-google-cdn ´´´ +1

**Comment by Hopefulee** [comment]
npm install grunt-google-cdn+1

**Comment by javarch** [comment]
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] Grunt breaks no matter what (#275)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'


Der Austausch von Nachrichten mit o.a. Absender via e-mail dient
ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen d�rfen
�ber dieses Medium nicht ausgetauscht werden.

Correspondence with a.m. sender via e-mail is only for information
purposes. This medium is not to be used for the exchange of legally-binding
communications.

**Comment by kobkrit** [comment]
npm install grunt-google-cdn +1

**Comment by OleksandrPoltavets** [comment]
> npm install grunt-google-cdn

 +1

**Comment by fredchu** [comment]
npm install grunt-google-cdn +1
