### ISSUE TITLE
Generator gets stuck during npm & bower install

### ISSUE THREAD

**Issue by eddiemoore** [yeoman/generator-angular#565]
I was just trying to setup a new project at work and the generator wouldn't finish running. seems to be getting stuck at the point of installing the **grunt-** files

I looked at the logs and a few things I found were:

```
npm ERR! Error: ENOENT, lstat '/<project_folder>/node_modules/grunt/package.json'
```

```
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/es5-shims/es5-shim.git", exit code of #128

Additional error details:
remote: Repository not found.
fatal: repository 'https://github.com/es5-shims/es5-shim.git/' not found
```

```
/Users/edward.moore/npm/lib/node_modules/generator-angular/node_modules/wiredep/lib/detect-dependencies.js:55
  if (_.isString(componentConfigFile.main)) {
                                    ^
TypeError: Cannot read property 'main' of undefined
    at findMainFiles (/Users/edward.moore/npm/lib/node_modules/generator-angular/node_modules/wiredep/lib/detect-dependencies.js:55:37)
    at /Users/edward.moore/npm/lib/node_modules/generator-angular/node_modules/wiredep/lib/detect-dependencies.js:101:17
    at forOwn (/Users/edward.moore/npm/lib/node_modules/generator-angular/node_modules/wiredep/node_modules/lodash/dist/lodash.js:1301:15)
    at Function.forEach (/Users/edward.moore/npm/lib/node_modules/generator-angular/node_modules/wiredep/node_modules/lodash/dist/lodash.js:2595:9)
    at detect (/Users/edward.moore/npm/lib/node_modules/generator-angular/node_modules/wiredep/lib/detect-dependencies.js:290:5)
    at module.exports (/Users/edward.moore/npm/lib/node_modules/generator-angular/node_modules/wiredep/bin/wiredep:34:40)
    at Generator._injectDependencies (/Users/edward.moore/npm/lib/node_modules/generator-angular/app/index.js:286:5)
    at /Users/edward.moore/npm/lib/node_modules/generator-angular/node_modules/yeoman-generator/node_modules/async/lib/async.js:229:13
    at /Users/edward.moore/npm/lib/node_modules/generator-angular/node_modules/yeoman-generator/node_modules/async/lib/async.js:110:21
    at /Users/edward.moore/npm/lib/node_modules/generator-angular/node_modules/yeoman-generator/node_modules/async/lib/async.js:24:16
```

Would any of these things be causing the generator to get stuck?

Any help on this issue would be great.

OS X: 10.9.1
node: v0.10.25
npm: 1.3.24
yo: 1.1.2
generator-angular: 0.7.1

**Comment by pserracomas** [comment]
running  'bower cache clean' and 'npm cache clean' worked for me as well, thanks!

**Comment by lancasja** [comment]
```bower cache clean``` and ```npm cache clean``` did the trick for me as well!
