### ISSUE TITLE
can't find lodash?

### ISSUE THREAD

**Issue by thedug** [yeoman/generator-angular#957]
After a fresh install of the generator with no errors, it complains about lodash being missing.
Then I install lodash. Same thing.

```
yo@1.1.2 /home/vagrant/npm/lib/node_modules/yo
├── open@0.0.4
├── async@0.2.10
├── shelljs@0.2.6
├── lodash@2.4.1
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── nopt@2.1.2 (abbrev@1.0.5)
├── findup@0.1.5 (commander@2.1.0, colors@0.6.2)
├── sudo-block@0.3.0 (chalk@0.3.0)
├── update-notifier@0.1.10 (semver@2.3.2, request@2.51.0, configstore@0.3.1)
├── insight@0.3.1 (object-assign@0.1.2, lodash.debounce@2.4.1, request@2.27.0, configstore@0.2.3, inquirer@0.4.1)
└── yeoman-generator@0.16.0 (dargs@0.1.0, debug@0.7.4, diff@1.0.8, class-extend@0.1.1, rimraf@2.2.8, findup-sync@0.1.3, text-table@0.2.0, mime@1.2.11, mkdirp@0.3.5, isbinaryfile@2.0.3, underscore.string@2.3.3, iconv-lite@0.2.11, glob@3.2.11, request@2.30.0, download@0.1.19, cheerio@0.13.1, file-utils@0.1.5, inquirer@0.4.1)
vagrant@vagrant-ubuntu-trusty-64:~/app/yo/angular$
vagrant@vagrant-ubuntu-trusty-64:~/app/yo/angular$
vagrant@vagrant-ubuntu-trusty-64:~/app/yo/angular$
vagrant@vagrant-ubuntu-trusty-64:~/app/yo/angular$
vagrant@vagrant-ubuntu-trusty-64:~/app/yo/angular$ yo angular

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-angular/node_modules/yeoman-generator/lib/env/index.js:8:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
vagrant@vagrant-ubuntu-trusty-64:~/app/yo/angular$ npm install lodash
npm http GET https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/lodash
lodash@2.4.1 node_modules/lodash
vagrant@vagrant-ubuntu-trusty-64:~/app/yo/angular$ yo angular

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-angular/node_modules/yeoman-generator/lib/env/index.js:8:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by marcinwal** [comment]
HI, I have the same problem. http://yeoman.io/authoring/composability.html .

Could you let me know how you solved it?

**Comment by smasala** [comment]
To fix the `Cannot find module 'lodash'` error, update node and npm as @eddiemonge stated. If anyone encounters this while attempting to [create their own generator](http://yeoman.io/authoring/user-interactions.html) then you will need to run `npm link` inside the generator directory again after you have run the updates.

**Comment by eddiemonge** [comment]
npm link only works if you have linked something. it runs npm update also so thats what you are seeing.

**Comment by smasala** [comment]
:+1:
